apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-node-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nick-cognizant/nick-demo-manifest.git'
    targetRevision: HEAD
    path: mychart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}